### ISSUE TITLE
zadanie

### ISSUE THREAD

**Issue by soownic** [grupa-programistyczna-igristoje/pyzia#1]
**# zrób program, który cały czas pyta użytkownika o liczbę, a jeśli poda liczbę 5, to napisze na ekranie "5 zamyka program" i program się zamyka.**

**Comment by soownic** [comment]
aha no i to wszystko zrób w nowym projekcie żeby było lepiej
zapisz jako zadanie jakoś tam

**Comment by soownic** [comment]
aha no i to wszystko zrób w nowym projekcie żeby było lepiej
zapisz jako zadanie jakoś tam

**Comment by likearockets** [comment]
zrobione synek

**Comment by soownic** [comment]
dobra daje -5, bo w sumie użyłeś chara do cyfry
